# Generated by Django 3.2.11 on 2024-05-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_d', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id_r', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Auto-route', 'Auto-route'), ('National', 'National'), ('Rurale', 'Rurale')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_v', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id_vo', models.AutoField(primary_key=True, serialize=False)),
                ('datev', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='home.driver')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='home.road')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='home.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id_a', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='home.voyage')),
            ],
        ),
    ]
